version: "3"
services:

  db:
    image: postgres:10.4
    ports:
      - "5432:5432"


  api:
    hostname: API
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db